name: snackbar
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  at_client_mobile: ^3.2.6
  at_utils: ^3.0.11
  path_provider: ^2.0.11
  flutter_dotenv: ^5.0.2
  at_app_flutter: ^5.0.1
  at_onboarding_flutter: ^5.0.3
  biometric_storage: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

